version: '3.9'
services:
  redis:
    image: redis:7.0.8-alpine
    ports:
      - 6379:6379
    volumes:
      - redis-limiter-data:/data
  api:
    build: .
    env_file: .env
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - redis

volumes:
  redis-limiter-data:
