version: '3.9'
services:
  redis:
    image: redis:7.0.8-alpine
    ports:
      - 6379:6379
    volumes:
      - redis-limiter-data:/data
  api:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
  
volumes:
  redis-limiter-data:
